---
# File: linux/roles/couchbase-server/centos/tasks/main.yml
# CentOS tasks for the Couchbase Server role
#
# Configure iptables, install Couchbase Server

- name: Configure iptables
  template: src=iptables.j2 dest=/etc/sysconfig/iptables.couchbase-server owner=root group=root
  notify:
  - lokkit
  when: firewall is defined
  tags: network

- name: Download Couchbase Server
  get_url: "url={{ centos.url }} dest=/tmp/{{ centos.package }} sha256sum={{ centos.sha256 }}"
  tags: installation
  
- name: Install Couchbase Server
  yum: "name=/tmp/{{ centos.package }} state=present"
  tags: installation

- name: Clean up
  file: "path=/tmp/{{ centos.package }} state=absent"
  tags: installation

- name: Start Couchbase Server service
  service: name=couchbase-server state=started
  tags: service
